### ISSUE TITLE
Wrong ISO short-code for ukrainian lang

### ISSUE THREAD

**Issue by Oxyaction** [yiiext/imperavi-redactor-widget#105]
Asset file with ukrainian named ua.js, but according to ISO-639 http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
it should be named uk, so i get an 404 loading uk.js asset in application when initializing widget
with
```php
'options' => array(
     'minHeight' => 130,
     'lang' => Yii::app()->language,
),
```
and that causes js error

**Comment by resurtm** [comment]
Even if we'll fix this, this must be posted to Imperavi Redactor developers (upstream). Isn't it?

**Comment by samdark** [comment]
I guess they're using another naming system. If you can find out which it would be easier to make a decision about what to do with it.
