### ISSUE TITLE
Release 10.0.8

### ISSUE THREAD

**Issue by a-komarev** [yiiext/imperavi-redactor-widget#106]
Alexander, could you update your extension to newest version of script, please?
There is a fix in this build included from the [forum thread](http://www.yiiframework.com/forum/index.php/topic/62159-imperavi-redactor-widget-breaking/page__pid__275447#entry275447).

**Comment by juukie** [comment]
There is a 10.0.9 already :). Please update.

**Comment by josephlimb** [comment]
+1 for updating.

**Comment by thedotedge** [comment]
:+1:

**Comment by a-komarev** [comment]
@samdark could you do the update, please?

**Comment by nikitakls** [comment]
+1 for updating.

**Comment by samdark** [comment]
https://github.com/yiiext/imperavi-redactor-widget/releases/tag/v1.3.9

**Comment by a-komarev** [comment]
Thanks a lot!

**Comment by juukie** [comment]
Thanks!
