### ISSUE TITLE
Change button class

### ISSUE THREAD

**Issue by nicolasiensen** [yiiext/imperavi-redactor-widget#112]
I wish to change the default buttons classes, in my case I want to use FontAwesome classes like ```.fa-bold``` and ```.fa-italic```.

If it was possible to do it in the settings parameter, it could look like this:

```js
$('.redactor').redactor({
  buttons: {
    bold: {
      class: "fa fa-bold"
    },
    italic: {
      class: "fa fa-italic"
    }
  }
});
```

What do you think? Does it make sense?

**Comment by samdark** [comment]
Yes. But this is not repository of Redactor itself so you should write to their support email.

**Comment by nicolasiensen** [comment]
Got it, thanks.
