### ISSUE TITLE
Image upload not being displayed in text editor

### ISSUE THREAD

**Issue by adrianmann** [yiiext/imperavi-redactor-widget#115]
Hi, If I drag an image from my local computer to the edit field everything runs smoothly in that the selected image is displayed in the text editor. However, when I try to insert the same image file from a local computer by clicking on the 'Browse' button in IE 11, I get the following errors: 

> "SCRIPT65535: Invalid calling object" 

and 

> "SCRIPT5007: Unable to get property '0' of undefined or null reference" and the image is not displayed as expected.

I am using Redactor 9 and this error only appears in IE 11. Everything is working as expected in Chrome, Firefox and Safari.

**Comment by samdark** [comment]
Please report to imperavi team via email `support@imperavi.com`. They don't have issue tracker as far as I know.
