### ISSUE TITLE
Compatibility with Yii2?

### ISSUE THREAD

**Issue by asakasinsky** [yiiext/imperavi-redactor-widget#118]
Hi, @samdark!
Please tell mе, 
this widget is compatible with the second version of the Yii framework?

**Comment by SDKiller** [comment]
@asakasinsky 

https://github.com/vova07/yii2-imperavi-widget

https://github.com/asofter/yii2-imperavi-redactor

**Comment by asakasinsky** [comment]
@SDKiller, I have seen these links, but I understood. I did not pay attention to the differences in the codestyle. In this widget - old codestyle VS widgets on your links.
Thank you/
