### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by atmoz** [yiiext/imperavi-redactor-widget#121]
Hi, I'm a little confused now. What version of Yii is supported, and why do the [plugin homepage](https://imperavi.com/redactor/log/) only say versions 1.x.x and in this repository it says 10.x.x?

Found another repository using the 10.x.x version numbering: https://github.com/vova07/yii2-imperavi-widget

What is going on?

**Comment by atmoz** [comment]
I found this: https://imperavi.com/blog/redactor-superior-in-every-way/

So the latest Redactor 2 is v1.x.x, while the latest Redactor 1 had v10.x.x.

But it would be nice if the readme in this repository told us what version of Yii is supported.

**Comment by samdark** [comment]
@atmoz This extension if for 1.1.x. vova07 is for 2.0.x. The redactor licensed to Yii as OEM is v1. We don't have OEM for version 2.
