### ISSUE TITLE
How to join your organization(yiiext)？

### ISSUE THREAD

**Issue by su-xiaolin** [yiiext/imperavi-redactor-widget#122]

**Comment by samdark** [comment]
It's pretty much about Yii 1.1 extensions. Do you want to maintain these?

**Comment by su-xiaolin** [comment]
forget it ![image](https://cloud.githubusercontent.com/assets/4076198/11242589/9e8eaff2-8e3d-11e5-9a86-7dfb0e96a1fb.png)
.
