### ISSUE TITLE
New plugin codemirror required

### ISSUE THREAD

**Issue by aztech** [yiiext/imperavi-redactor-widget#123]
Could you be so kind to add following plugin https://imperavi.com/redactor/plugins/codemirror/ into this repository?

**Comment by SDKiller** [comment]
@aztech 

> This plugin is only compatible with Redactor II ...

**Comment by aztech** [comment]
Ahh.... I miss that small written "II".
Can we expect that Redactor II will OEM licensed for Yii/Yii2 too?

**Comment by samdark** [comment]
No. The license isn't compatible.
