### ISSUE TITLE
Problems switching between ordered and unordered lists

### ISSUE THREAD

**Issue by jpruiz114** [yiiext/imperavi-redactor-widget#124]
Hello, I'm using the latest version of the redactor library that can be found in your repo here:

https://github.com/yiiext/imperavi-redactor-widget/blob/master/assets/redactor.js

When you add some text to the editor, let's say for example:

aaaa
bbbb
cccc
dddd

... and then select it and decide to convert that text into an ordered list the first time you click the ordered list button you will get the ordered list, as expected, but if you click again that same button, you would expect the order list to disappear but that doesn't happen, what happens is that it becomes an unordered list.

Are you aware of this bug?

Do you have any ideas on how to implement a workaround?

I'm using the following code:

https://jsfiddle.net/jpruiz114/71uwpazo/

```html
<!DOCTYPE html>
<html>
	<head>
		<title>Test 1</title>
		
		<meta charset="utf-8">
		
		<script src="https://code.jquery.com/jquery-1.12.2.min.js"></script>
		
		<link rel="stylesheet" href="assets/redactor.css" />
		
		<script src="assets/redactor.js"></script>
		
		<script type="text/javascript">
			$(
				function() {
					$('#content').redactor();
				}
			);
		</script>
	</head>
	
	<body>
		<textarea id="content" name="content"></textarea
	</body>
</html>
```

Thanks!

Edit 1:

I have tested with the version 10.2.5 Updated on October 1, 2015 and with the version 10.2.2 Updated on July 15, 2015 and the same behaviour happens.

**Comment by jpruiz114** [comment]
```html
<script async src="//jsfiddle.net/jpruiz114/71uwpazo/embed/"></script>
```

**Comment by jpruiz114** [comment]
<script async src="//jsfiddle.net/jpruiz114/71uwpazo/embed/"></script>

**Comment by jpruiz114** [comment]
<script async src="//jsfiddle.net/jpruiz114/71uwpazo/embed/"></script>

**Comment by samdark** [comment]
Not the issue of the widget. Please report to Redactor itself.
