### ISSUE TITLE
Properties plugin

### ISSUE THREAD

**Issue by CyanoFresh** [yiiext/imperavi-redactor-widget#127]
Hello. Does license give access to this plugin http://imperavi.com/redactor/plugins/properties/ ?
If so can you please add this to your rep?

**Comment by samdark** [comment]
I think this one if for new redactor. Our license is for old one only.

**Comment by CyanoFresh** [comment]
hm, okay. so sad. I thought bought software should be maintained and upgraded to the new version

**Comment by samdark** [comment]
Well, that does not depend on us.
