### ISSUE TITLE
redactor removes certain character on submit

### ISSUE THREAD

**Issue by hesna** [yiiext/imperavi-redactor-widget#74]
There is a half-space character in Persian and Arabic languages that redactor removes before submitting the text.
```
میروم
می‌روم
می روم
```
as you can see, the second word uses the half-space character I mentioned before. it is inserted in text using shift+space in unix based systems and is very useful and standard in those languages. but redactor changes the second word to first word (removes half-space) and sends it to server.

this is an issue with redactor, other text editors do not behave like this, how can I fix this? 

P.S.: I've checked redactor version 8.1 and it wasn't an issue those days, but that version is too old to be useful for my current project, I'm using v9.2.4 .

**Comment by hadifarnoud** [comment]
@hesna how did you fix it?

**Comment by hesna** [comment]
@hadifarnoud by editing the JS file and commenting responsible line.. could not find any other way. I don't remember which line it was.
