### ISSUE TITLE
Upload Image in ie get response header application/json

### ISSUE THREAD

**Issue by hueitan** [yiiext/imperavi-redactor-widget#76]
Upload Image in ie get `response header` `application/json`

Then I got the

![screen shot 2014-06-24 at 3 02 53 am](https://cloud.githubusercontent.com/assets/2560096/3362385/308e809a-fb09-11e3-9ac4-cf6446d408c0.png)

Download the .json file not use the .json data as json type

---

I can't successful upload image

**Comment by adrianmann** [comment]
@huei90 Why was this closed? What is the solution please?

**Comment by adrianmann** [comment]
@huei90 I updated to the latest version of Redactor and the bug was gone.

**Comment by huei90** [comment]
ie8 is unable to understand the response data in `application/json` type, therefore I changed it to `text/html`.

But I'm not sure the latest version using which type of response

**Comment by adrianmann** [comment]
@huei90 Okay, thanks, there is no error in the latest version.
