### ISSUE TITLE
underline shortcut key

### ISSUE THREAD

**Issue by huei90** [yiiext/imperavi-redactor-widget#84]
@samdark Would you mind transfer this message to the Redactor team?

In these line
https://github.com/yiiext/imperavi-redactor-widget/blob/master/assets/redactor.js#L109-L118

should add the underline shortcut key
```
'ctrl+u, meta+u': "this.execCommand('underline', false)"
```

I'm wondering why underline is not set by default

====

UPDATE

i found there is an opt `shortcutsAdd`

**Comment by 14falcons** [comment]
@samdark   Did you get shortcutsAdd to work?  If so, would you please share the specific command.

Will this do it?  

$('#redactor').redactor({
    shortcutsAdd:
    {
        'ctrl+u, cmd+u’: { func: 'underline', params: ['underline'] },
    }
});


Thanks.

**Comment by kcliu** [comment]
solution provided by @14falcons works
